### ISSUE TITLE
Null Pointer when generating reports

### ISSUE THREAD

**Issue by dannyviti** [damianszczepanik/cucumber-reporting-jenkins#120]
Upgraded to 0.0.23, some json files will generate an HTML report fine. However I have one that is generating a NPE and causing the build to fail. 

When I check it at cucumber-reporting.masterthought.net, it generates the report fine. Is it possible I need to move to 0.0.24? I can send the json if that would be helpful.

there was an error generating the reports: java.lang.NullPointerException
net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:76)
net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:112)
hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
hudson.model.Build$BuildExecution.post2(Build.java:182)
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
hudson.model.Run.execute(Run.java:1731)
hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
hudson.model.ResourceController.execute(ResourceController.java:88)
hudson.model.Executor.run(Executor.java:232)
Build step 'Publish cucumber results as a report' changed build result to FAILURE

Thanks for your help.
Danny

**Comment by dannyviti** [comment]
I did try the 0.0.24 release, similar error:
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from slave: /home/jenkins/workspace/workbench_web_behavior_testing_iso/reports to master reports directory: /var/lib/jenkins/jobs/workbench_web_behavior_testing_iso/builds/2015-04-06_08-01-33/cucumber-html-reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.NullPointerException
	at org.apache.tools.ant.DirectoryScanner.normalizePattern(DirectoryScanner.java:797)
	at org.apache.tools.ant.DirectoryScanner.setExcludes(DirectoryScanner.java:751)
	at net.masterthought.jenkins.CucumberReportPublisher.findJsonFiles(CucumberReportPublisher.java:59)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:182)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)

**Comment by kingsleyh** [comment]
Does that only happen when using a slave?

**Comment by dannyviti** [comment]
Currently I've only tried running it on the slaves. Haven't tried tying particular jobs to the master. I can give that a try but might not work well for our set up. I'll update if I can kick that job off tied to the master today.
Thanks

**Comment by dannyviti** [comment]
Doesn't look that easy in our set up b/c our master node doesn't have all the packages that it needs to run these jobs. Sorry I can't verify the master only question.

**Comment by kingsleyh** [comment]
If I send you a custom hpi are you able to test it out?

**Comment by kingsleyh** [comment]
Also maybe email me your json to kingsley at MasterThought dot net

**Comment by sandeep89** [comment]
hi Kingsleyh, we did ran in to the same issue. 
This looks like a JSON issue which occurred in our case when the data/variable which we were trying to print was empty hence the JSON was incompatible with the Java JSON library. Below is a sample JSON which is created
```
{
            "keyword": "When ",
            "name": "Dummy test case",
            "line": 53,
            "output": [
              [

              ]
            ],
            "match": {
              "location": "/scenario1/testcases1:172"
            },
            "result": {
              "status": "passed",
              "duration": 4311254926
            }
          }
```

**Comment by dannyviti** [comment]
I've sent the json and yes I can test a custom hpi.
Thanks for your help.
Danny

**Comment by gboucherie** [comment]
Hi,

I think it's not the same issue on two version.
In version 0.0.24 the NPE is located in ant lib when it try to scan the directory with includes and excludes pattern.
Maybe you should not set the exclude option when exclude pattern is not provided by user ?

Best Regards,

Guillaume

**Comment by alexeyts** [comment]
Same thing happens to us on 0.0.24.
Any news on this issue?

java.lang.NullPointerException
	at org.apache.tools.ant.DirectoryScanner.normalizePattern(DirectoryScanner.java:797)
	at org.apache.tools.ant.DirectoryScanner.setExcludes(DirectoryScanner.java:751)
	at net.masterthought.jenkins.CucumberReportPublisher.findJsonFiles(CucumberReportPublisher.java:59)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1037)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by kingsleyh** [comment]
I will investigate

**Comment by beemi** [comment]
any update on this 

Thank you

**Comment by fenchu** [comment]
v0.0.24 Works fine on master, not on slave:
[CucumberReportPublisher] copying all json files from slave: C:\jenkins\workspace\AtsNtIs_RecurringPay_Integration_Tests_by_param to master reports directory: C:\Jenkins\jobs\AtsNtIs_RecurringPay_Integration_Tests_by_param\builds\25\cucumber-html-reports
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.apache.tools.ant.DirectoryScanner.normalizePattern(DirectoryScanner.java:797)

**Comment by damianszczepanik** [comment]
Logs are similar to #125

**Comment by ojbMMXV** [comment]
Getting very similar looking results on version 1.0.0. Has only occurred since upgrading from 0.0.19.

    [CucumberReportPublisher] Found 6 json files.
    ...
    [CucumberReportPublisher] Generating HTML reports
    [CucumberReportPublisher] there was an error generating the reports: java.lang.NullPointerException
    net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:136)
    net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:139)
    hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:736)
    hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1030)
    hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:685)
    hudson.model.Run.execute(Run.java:1757)
    hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:519)
    hudson.model.ResourceController.execute(ResourceController.java:88)
    hudson.model.Executor.run(Executor.java:234)
    Build step 'Publish cucumber results as a report' changed build result to FAILURE
