### ISSUE TITLE
Null reference exception in 0.0.24

### ISSUE THREAD

**Issue by imakowski** [damianszczepanik/cucumber-reporting-jenkins#125]
After updating from version 0.0.23 to 0.0.24 i have following exception:

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from slave: c:\jenkins\j-W7FF\workspace\F10\BVT\Selenium\DBType\S14W122\Node\PL&&Selenium\SeleniumBrowser\FF to master reports directory: d:\jenkinslogs\F10\BVT\Selenium\DBType=S14W122,Node=PL&&Selenium,SeleniumBrowser=FF\builds\2015-04-22_08-12-09\cucumber-html-reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.NullPointerException
	at org.apache.tools.ant.DirectoryScanner.normalizePattern(DirectoryScanner.java:797)
	at org.apache.tools.ant.DirectoryScanner.setExcludes(DirectoryScanner.java:751)
	at net.masterthought.jenkins.CucumberReportPublisher.findJsonFiles(CucumberReportPublisher.java:59)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by damianszczepanik** [comment]
Looks like problem with dependencies or Jenkins. Can you attach json file?

**Comment by damianszczepanik** [comment]
A few new version have been published from that time
