### ISSUE TITLE
org.apache.velocity.exception.MethodInvocationException

### ISSUE THREAD

**Issue by slott** [damianszczepanik/cucumber-reporting-jenkins#131]
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getFileName' in class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at templates/featureOverview.vm[line 389, column 73]

**Comment by simonmulser** [comment]
same here when clicking in jenkins on the reports...

**Comment by slott** [comment]
Just updated to 0.2.1 and the issue remains.

**Comment by damianszczepanik** [comment]
Issue is already fixed and will be published with next release. You can find what to do to fix the problem

https://github.com/damianszczepanik/cucumber-reporting/issues/90

**Comment by harisharthanari** [comment]
I receive similar message with ReportNG configured in my maven project
Does any one have any inputs to share?

[TestNG] Reporter org.uncommons.reportng.HTMLReporter@70e38ce1 failed
org.uncommons.reportng.ReportNGException: Failed generating HTML report.
	at org.uncommons.reportng.HTMLReporter.generateReport(HTMLReporter.java:122)
	at org.testng.TestNG.generateReports(TestNG.java:1184)
	at org.testng.TestNG.run(TestNG.java:1109)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getUser' in  class org.uncommons.reportng.ReportMetadata threw exception class java.net.UnknownHostException : ip-10-0-5-235: ip-10-0-5-235: Temporary failure in name resolution
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:193)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:175)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:220)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.Template.merge(Template.java:256)
	at org.apache.velocity.app.Velocity.mergeTemplate(Velocity.java:449)
	at org.uncommons.reportng.AbstractReporter.generateFile(AbstractReporter.java:108)
	at org.uncommons.reportng.HTMLReporter.createOverview(HTMLReporter.java:148)
	at org.uncommons.reportng.HTMLReporter.generateReport(HTMLReporter.java:111)

**Comment by damianszczepanik** [comment]
Have you read this message https://github.com/damianszczepanik/cucumber-reporting-jenkins ?
