### ISSUE TITLE
com.google.gson.JsonSyntaxException jenkins build fails 

### ISSUE THREAD

**Issue by omidomi33** [damianszczepanik/cucumber-reporting-jenkins#159]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28
    at com.google.gson.JsonParser.parse(JsonParser.java:65)
    at com.google.gson.JsonParser.parse(JsonParser.java:45)
    at com.hp.mercury.ci.jenkins.plugins.oo.core.OOAccessibilityLayer.run10x(OOAccessibilityLayer.java:170)
    at com.hp.mercury.ci.jenkins.plugins.OOBuildStep.perform(OOBuildStep.java:691)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
    at com.google.gson.JsonParser.parse(JsonParser.java:60)

**Comment by SunmerCho** [comment]
Hi, i have the same issue, did you work it out?  I need some help if you did please.

**Comment by damianszczepanik** [comment]
Show me the JSON file

**Comment by SunmerCho** [comment]
I try to build a project which i download form [github,](https://github.com/NordicSemiconductor/Android-nRF-Beacon-for-Eddystone)
 it build failed and show the error messeage 
Error:Execution failed for task ':app:processDebugGoogleServices'.

> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10
> I do not konw how to see the details.

**Comment by damianszczepanik** [comment]
Show me the JSON file

**Comment by SunmerCho** [comment]
It is  a new project,i do not know where the JSON file it parsed.It did not throws JsonSyntaxException, i think it is not JSON parse problem, perhaps.
