### ISSUE TITLE
Crash when step has no result section

### ISSUE THREAD

**Issue by malavikac** [damianszczepanik/cucumber-reporting-jenkins#163]
I have set hudson.model.DirectoryBrowserSupport.CSP to null which starting jenkins.
But when I open cucumber jvm report, It is reseting this value to "sandbox allow-same-origin allow-scripts; script-src 'self' 'unsafe-inline'; default-src 'self'; img-src 'self'; style-src 'self'" . 
This in turn failing other plugin reports.
Version of cucumber plugin : 2.5.1

**Comment by malavikac** [comment]
Hi,
Can you please look into this issue. It blocking us from using this plugin.

**Comment by damianszczepanik** [comment]
Upgrade the plugin

**Comment by malavikac** [comment]
In the latest version Json itself is not creating. So i have downgraded to this version. In this version json and cucumber files are created but CSP is updating automatically.

**Comment by damianszczepanik** [comment]
Plugin needs json as input not output

**Comment by malavikac** [comment]
Yes. When I upgrade to latest version(3.3.0), This is the error I am getting. Which I was not getting in 2.5.2 
java.lang.NullPointerException
	at net.masterthought.cucumber.json.Element.calculateStepsStatus(Element.java:120)
	at net.masterthought.cucumber.json.Element.setMetaData(Element.java:96)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:161)
	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:97)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:60)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:76)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:123)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:73)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceControlle
[cucumber.zip](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/681620/cucumber.zip)

r.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)

Attached Jason report for the same.

**Comment by damianszczepanik** [comment]
steps have no `results` section and it makes them problematic - I don't have a plan in near feature to supporting such case
