### ISSUE TITLE
Cucumber reports are giving 'Publish Cucumber test result report’ aborted due to exception : java null exception in jenkins

### ISSUE THREAD

**Issue by YugandharBandari** [damianszczepanik/cucumber-reporting-jenkins#171]
Hi Team,

I'm getting below mentioned errors while trying to generate the Cucumber reports in jenks

used below mentioned files:
Jenkins : 2.87
Cucumber reports hpi : 3.11
junit : 4.12

ERROR: Step ‘Publish Cucumber test result report’ aborted due to exception: 
java.io.IOException: Expecting Ant GLOB pattern, but saw 'C:\Users\502147204\workspace\TKCucumber\Reports'. See http://ant.apache.org/manual/Types/fileset.html for syntax
	at hudson.FilePath.glob(FilePath.java:1756)
	at hudson.FilePath.access$1700(FilePath.java:196)
	at hudson.FilePath$32.invoke(FilePath.java:1736)
	at hudson.FilePath$32.invoke(FilePath.java:1733)
	at hudson.FilePath.act(FilePath.java:997)
	at hudson.FilePath.act(FilePath.java:975)
	at hudson.FilePath.list(FilePath.java:1733)
	at hudson.FilePath.list(FilePath.java:1717)
	at hudson.FilePath.list(FilePath.java:1702)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:136)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:107)
	at hudson.FilePath.act(FilePath.java:997)
	at hudson.FilePath.act(FilePath.java:975)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl.parseResult(DefaultTestResultParserImpl.java:101)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parseResult(CucumberJSONParser.java:101)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.publishReport(CucumberTestResultArchiver.java:128)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:107)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finished: FAILURE

Thanks,
Yugi

**Comment by damianszczepanik** [comment]
This fork is closed

**Comment by YugandharBandari** [comment]
can you ans this question
