### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile

### ISSUE THREAD

**Issue by ghost** [damianszczepanik/cucumber-reporting-jenkins#175]
ERROR:

java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at net.masterthought.cucumber.ReportBuilder.copyResources(ReportBuilder.java:141)
	at net.masterthought.cucumber.ReportBuilder.copyStaticResources(ReportBuilder.java:120)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:79)
	at CucumberReport.genrateCucumberMavenRepor(CucumberReport.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Dependency:
<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>maven-cucumber-reporting</artifactId>
			<version>4.7.0</version>
			<scope>test</scope>
		</dependency>

Src code:
![image](https://user-images.githubusercontent.com/55419665/66494601-ec72b080-ea85-11e9-80bb-7353413f8979.png)

![image](https://user-images.githubusercontent.com/55419665/66494630-fbf1f980-ea85-11e9-94e2-b3d4d73b071c.png)

looks like there is a new version of filUtils or that method deprecated ?

Any help will be much appropriated.

**Comment by ghost** [comment]
I am sorry... I have old commons-io library hence this issue. I am  good now. please close this ticket.
