### ISSUE TITLE
[Ruby]Error when generating report

### ISSUE THREAD

**Issue by yasuoza** [damianszczepanik/cucumber-reporting-jenkins#33]
Hi,

This plugin seems cool, so I tried this but  failed when generating report.

Following error message was shown in jenkins job console.

````
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: /var/lib/jenkins/jobs/RingNote-AT/builds/2012-08-24_17-03-50/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:757)
	at com.google.gson.Gson.fromJson(Gson.java:706)
	at com.google.gson.Gson.fromJson(Gson.java:678)
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:30)
	at net.masterthought.cucumber.ReportParser.<init>(ReportParser.java:18)
	at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:31)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:710)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:685)
	at hudson.model.Build$RunnerImpl.post2(Build.java:162)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:632)
	at hudson.model.Run.run(Run.java:1463)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:239)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:306)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:791)
	... 16 more
````

Error message seems like issue #17, but I'm using  cucumber-reports version 0.0.14 on jenkins 1.466.1.
Thank you for help.

**Comment by seleniumbheema** [comment]
Still I'm getting this issue, please see my Error below

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.298 s
[INFO] Finished at: 2015-10-28T14:59:20+00:00
[INFO] Final Memory: 11M/310M
[INFO] ------------------------------------------------------------------------
ERROR: Maven JVM terminated unexpectedly with exit code 0
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: /Users/Shared/Jenkins/Home/jobs/Appium_IOS_maven/builds/45/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
Finished: FAILURE

**Comment by damianszczepanik** [comment]
Did you check this first?
https://www.google.pl/search?q=ERROR:+Maven+JVM+terminated+unexpectedly+with+exit+code+0

**Comment by seleniumbheema** [comment]
@damianszczepanik i've tired everything but still getting below error.

i can email you my POM xml, if you want. 

ERROR: Maven JVM terminated unexpectedly with exit code 1
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: /Users/Shared/Jenkins/Home/jobs/Appium_IOS_maven/builds/59/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
Finished: FAILURE

**Comment by damianszczepanik** [comment]
Attach json file so I can check if this is plugin problem or the source is located out of the plugin.
