### ISSUE TITLE
404 on cucumber-jvm reports

### ISSUE THREAD

**Issue by mesmacosta** [damianszczepanik/cucumber-reporting-jenkins#45]
getting a 404 on the cucumber-jvm plugin.

After running the plugin, when i click on the cucumber reports button, i get an empty stacktrace:

Status Code: 404

Exception: 
Stacktrace:

using jenkins 1.491
and plugin 0.19

DSV Cucumber #43 main build action completed: SUCCESS
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
at com.google.gson.Gson.fromJson(Gson.java:802)
at com.google.gson.Gson.fromJson(Gson.java:757)
at com.google.gson.Gson.fromJson(Gson.java:706)
at com.google.gson.Gson.fromJson(Gson.java:678)
at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:30)
at net.masterthought.cucumber.ReportParser.<init>(ReportParser.java:18)
at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:36)
at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:100)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:779)
at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:939)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:726)
at hudson.model.Run.execute(Run.java:1541)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:477)
at hudson.model.ResourceController.execute(ResourceController.java:88)
at hudson.model.Executor.run(Executor.java:236)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:306)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
at com.google.gson.Gson.fromJson(Gson.java:791)

**Comment by ravishankar** [comment]
I am also facing same issue, 
I have two instances of Jenkins, same plug in is working fine on windows where i have jenkins 1.601 version how ever on linux i have jenkins 1.534  , where i am getting 404 error mentioned above. 
Is there any java version dependency because on windows server i am running 1.8.0_65 JDK version & Linus is having 1.7.0_75 JDK ?
