### ISSUE TITLE
Cucumber reports link show a 404 error

### ISSUE THREAD

**Issue by Sjust** [damianszczepanik/cucumber-reporting-jenkins#52]
Hi,

I've read some issues about 404 error, maybe the solution of my problem is there but I'm not capable to find it.

My trouble is the next:

The plugin works fine during the execution:

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: /var/lib/jenkins/jobs/Spitni-UI_Testing_in_PreProd_RUBY/builds/2013-03-08_11-29-37/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
Finished: SUCCESS

I create the cucumber.json using this line in my execution:

bundle exec cucumber -p jenkins features/web/ --format json -o cucumber.json

This is the resultant json:

[{"uri":"features/web/check_home.feature","name":"Check the home page","description":"In order to be sure the home page is shown\nAs a Spitni visitor\nI want to see the home page properly","id":"check-the-home-page","line":1,"keyword":"Feature","elements":[{"steps":[{"name":"i am on the HomePage site","result":{"status":"passed"},"match":{"arguments":[{"offset":12,"val":"HomePage"}],"location":"features/step_definitions/web_shared_steps.rb:33"},"line":9,"keyword":"Given "},{"name":"I should see the products content block","result":{"status":"passed"},"match":{"arguments":[{"offset":17,"val":"products content"}],"location":"features/step_definitions/web_shared_steps.rb:6"},"line":10,"keyword":"Then "}],"name":"Open the home page","description":"As a unregistered user, when going to the home page\ni should be able to see the home page properly.","id":"check-the-home-page;open-the-home-page","line":6,"keyword":"Scenario","type":"scenario"}]},{"uri":"features/web/contact_request.feature","name":"Click on the contact link","description":"In order to look for the submitMessage button","id":"click-on-the-contact-link","line":1,"keyword":"Feature","elements":[{"steps":[{"name":"I am on the HomePage site","result":{"status":"passed"},"match":{"arguments":[{"offset":12,"val":"HomePage"}],"location":"features/step_definitions/web_shared_steps.rb:33"},"line":5,"keyword":"Given "},{"name":"I click on link Contact","result":{"status":"passed"},"match":{"arguments":[{"offset":16,"val":"Contact"}],"location":"features/step_definitions/web_shared_steps.rb:233"},"line":6,"keyword":"When "},{"name":"I should see the Contact page","result":{"status":"passed"},"match":{"arguments":[{"offset":17,"val":"Contact"}],"location":"features/step_definitions/web_shared_steps.rb:109"},"line":7,"keyword":"Then "}],"name":"Go to the homepage and click on the contact link and look for the submitMessage button","description":"","id":"click-on-the-contact-link;go-to-the-homepage-and-click-on-the-contact-link-and-look-for-the-submitmessage-button","line":4,"keyword":"Scenario","type":"scenario"}]}]

Do you see something wrong?

Thanks in advance,
Sergi Just Casas

**Comment by pambwani** [comment]
Hi I am getting this error in the url of cucumber reports 

Cucumber

Back To Jenkins
Oops Something went wrong with TestCucumber build: 15

The error message (if any) is below:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 380 path $[0].elements[0].before[0].match.location
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.Gson.fromJson(Gson.java:861)
    at com.google.gson.Gson.fromJson(Gson.java:799)
    at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:35)
    at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:48)
    at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:133)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 380 path $[0].elements[0].before[0].match.location
    at com.google.gson.stream.JsonReader.nextString(JsonReader.java:838)
    at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
    at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:410)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    ... 26 more

Trying to generate report from following files. Make sure they are valid cucumber report files: 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__16_12_4.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__16_16_11.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__16_8_39.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__17_0_54.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__17_44_45.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__17_59_41.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__18_59_25.json 
/root/.jenkins/jobs/TestCucumber/builds/15/cucumber-html-reports/Sauce_Android_android_device_5__19_2_47.json 

Jenkins Plugin | Cucumber reports 
build: 28-01-2016 19:04:37

**Comment by damianszczepanik** [comment]
It says that json file is not valid:
`BEGIN_OBJECT at line 1 column 380 path $[0].elements[0].before[0].match.location`

Attach JSON so I can check what's going on

**Comment by pambwani** [comment]
My json file is : 

[{"uri":"features/LoginOnBoarding.feature","id":"login-to-free-charge-app","keyword":"Feature","name":"Login to Free charge app","description":"  As I user I want to validate that the app behaves\n  as expected","line":2,"tags":[{"name":"@e2e","line":1}],"elements":[{"keyword":"Background","name":"","description":"","line":6,"type":"background","before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":[8]}}},"result":{"status":"passed","duration":13012}}],"steps":[{"keyword":"Given ","name":"I Start the Freecharge app","line":7,"output":["Starting freecharge app"],"match":{"location":{"filepath":{"filename":"features/step_definitions/Step_Login.rb"},"lines":{"data":[2]}}},"result":{"status":"passed","duration":10000200570}}]},{"id":"login-to-free-charge-app;login-to-app","keyword":"Scenario","name":"Login to app","description":"","line":11,"type":"scenario","tags":[{"name":"@e2e","line":1},{"name":"@login","line":10}],"steps":[{"keyword":"When ","name":"I select get started","line":12,"match":{"location":{"filepath":{"filename":"features/step_definitions/Step_Login.rb"},"lines":{"data":[8]}}},"result":{"status":"passed","duration":11671528229}},{"keyword":"When ","name":"I enter Username in email id field","line":13,"match":{"location":{"filepath":{"filename":"features/step_definitions/Step_Login.rb"},"lines":{"data":[13]}}},"result":{"status":"passed","duration":16405364864}},{"keyword":"And ","name":"password in Password field","line":14,"match":{"location":{"filepath":{"filename":"features/step_definitions/Step_Login.rb"},"lines":{"data":[18]}}},"result":{"status":"passed","duration":6857388992}}],"after":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":[12]}}},"result":{"status":"passed","duration":17944}}]}]}]

**Comment by pambwani** [comment]
I  am using ruby cucumber framework to do my automation and I get my reports in json format for cucumber plugin .. How can I refine this to get it working ? 

I use this function : 

 def json_report_flag(name)
  path = path_to_results_folder
  date_dir = date_folder
  uniq_postfix = unique_postfix
  create_directory(path, date_dir)
  report_name = "#{name}__#{uniq_postfix}.json"
  "-f json --out #{path}/#{date_dir}/#{report_name}"
end

and use it like this to generate reports 

task :android_avd, [:tag, :avd] do |t, args|
  Cucumber::Rake::Task.new :cucumber_android_avd do |t|
    ENV['DEVICE'] = args[:avd].to_s.gsub('avd:', '').strip

```
emulator = ENV['DEVICE']
tag = args[:tag]

t.profile = 'android_avd'

if tag.nil?
  t.cucumber_opts = json_report_flag("Android_#{emulator}")
else
  t.cucumber_opts = "--tags @#{tag.gsub('@', '')} #{json_report_flag("Android_#{emulator}")}"
end
```

  end

**Comment by damianszczepanik** [comment]
This plugin does not officially support ruby
