### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2

### ISSUE THREAD

**Issue by DeepDiver1975** [damianszczepanik/cucumber-reporting-jenkins#53]
````
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:757)
        at com.google.gson.Gson.fromJson(Gson.java:706)
        at com.google.gson.Gson.fromJson(Gson.java:678)
        at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:30)
        at net.masterthought.cucumber.ReportParser.<init>(ReportParser.java:18)
        at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:36)
        at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:100)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:814)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:786)
        at hudson.model.Build$BuildExecution.post2(Build.java:183)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:733)
        at hudson.model.Run.execute(Run.java:1592)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:237)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
        at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:306)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:791)
        ... 16 more

**Comment by damianszczepanik** [comment]
I was able to generate report using the most recent version

**Comment by huoyabingqian** [comment]
什么意思，看不懂
