### ISSUE TITLE
cucumber-html-report fails to display feature overview graphs when there are any pending steps

### ISSUE THREAD

**Issue by attr** [damianszczepanik/cucumber-reporting-jenkins#64]
cucumber-html-report displays
```html
	<div id="fullwidth_gradient">
		<div class="container_12">
			<div class="grid_9 heading">
				<h2 id="overview-title">Oops Something went wrong with ci-rnd-BDD-tests build: 147</h2>
				<span class="subhead">The error message (if any) is below:</span>
			</div>
		</div>
	</div>

	<div class="container_12">
		<div class="grid_12">

	<br>

	<div id="error-message" class="error-message">java.lang.NullPointerException</div>
```
instead of showing feature overview graphs when a pending step is introduced, i.e.:
```java
@Then("^pending step$")
public void pendingStep() {
    throw new PendingException();
}
```
I`m using Jenkins v.1.515 with cucumber-reporting v.0.0.21 and cucumber-jvm v.1.1.3.
Jenkins logs:
```log
INFO: ci-rnd-BDD-tests #147 main build action completed: SUCCESS
java.lang.NullPointerException
        at net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:63)
        at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:114)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:776)
        at hudson.model.Build$BuildExecution.post2(Build.java:183)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:726)
        at hudson.model.Run.execute(Run.java:1600)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:241)
```

**Comment by damianszczepanik** [comment]
Released
