### ISSUE TITLE
Cucumber Reports hangs whilst trying to publish results on Jenkins.

### ISSUE THREAD

**Issue by pjmoore92** [damianszczepanik/cucumber-reporting-jenkins#87]
Our build is running on Jenkins via a slave machine. The build finishes and moves onto parsing the JSON however this hangs indefinitely. (Tests should take ~ 6 hours - at 20 hours (the next morning) we just had to interrupt it)

Tests run: 33, Failures: 0, Errors: 13, Skipped: 6

Build was aborted
Aborted by username
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:146)
	at hudson.remoting.Channel.call(Channel.java:672)
	at hudson.FilePath.act(FilePath.java:893)
	at hudson.FilePath.act(FilePath.java:877)
	at hudson.FilePath.toURI(FilePath.java:1005)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:57)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:776)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:960)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:726)
	at hudson.model.Run.execute(Run.java:1600)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:486)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:241)
No emails were triggered.
Finished: ABORTED

Relevant Stack trace is the following:

at java.lang.Object.wait(Native Method) at hudson.remoting.Request.call(Request.java:146) at hudson.remoting.Channel.call(Channel.java:672) at hudson.FilePath.act(FilePath.java:893) at hudson.FilePath.act(FilePath.java:877) at hudson.FilePath.toURI(FilePath.java:1005) at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:57)

The JSON file is fine as far as I can tell (putting it into cucumber-reporting.masterthough.net compiled it).

Not sure what would be causing this as other projects run fine and reports generate ok.

**Comment by damianszczepanik** [comment]
Might be the same as https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/59
